### ISSUE TITLE
measurementStandard NLA, GLA vs nla, gla

### ISSUE THREAD

**Issue by weber-lars** [swissfintechinnovations/common-API#16]
propertyBuildingInformation.livingSpace.measurementStandard:
-	nla
-	gfa
-	Description: «The measurement standard used to determine the living space (NFA or GFA).»

propertyFlatInformation.livingSpace.measurementStandard:
-	NLA
-	GFA
-	Description: «The measurement standard used to determine the living space (NFA or GFA).»

**Comment by rolfwagner** [comment]
Patch -->2.0.2
